/*
 *  DocumentListener.java
 *  (ScissLib)
 *
 *  Copyright (c) 2004-2020 Hanns Holger Rutz. All rights reserved.
 *
 *  This software is published under the GNU Lesser General Public License v2.1+
 *
 *
 *	For further information, please contact Hanns Holger Rutz at
 *	contact@sciss.de
 */

package de.sciss.app;

import java.util.EventListener;

/**
 *  Interface for listening
 *  the changes of the list of documents
 *  of an application. They are
 *	usually generated by the <code>DocumentHandler</code>
 *	of the application.
 *
 *  @author		Hanns Holger Rutz
 *  @version	0.13, 02-Aug-05
 *
 *  @see	DocumentHandler
 */
public interface DocumentListener
extends EventListener
{
    /**
     *  Notifies the listener that
     *  a document has been created and added
     *	to the list of open documents.
     *
     *  @param  e   the event describing
     *				the change
     */
    public void documentAdded( DocumentEvent e );

    /**
     *  Notifies the listener that
     *  a document has been removed from
     *	the list of open documents and
     *	was destroyed.
     *
     *  @param  e   the event describing
     *				the change
     */
    public void documentRemoved( DocumentEvent e );

    /**
     *  Notifies the listener that
     *  a the active document has been switched.
     *	<code>e.getDocument</code> will return
     *	the newly active document (or <code>null</code>,
     *	if no document is active any more).
     *
     *  @param  e   the event describing
     *				the change
     */
    public void documentFocussed( DocumentEvent e );
}